[build-system]
requires = ["setuptools >= 66.1.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "srn"
readme = "README.md"
description = "Spaced repetition for Notes"
authors = [{ name = "Guillermo Rebaza", email = "grebaza@gmail.com" }]
dynamic = ["version"]
urls = { Homepage = "https://github.com/grebaza/sr-notes.git" }
keywords = ["spaced repetition", "note taking", "productivity"]
requires-python = ">=3.10"
license = { text = "MIT" }
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Operating System :: OS Independent",
]
dependencies = [
  "argcomplete ~= 3.3.0",
  "click ~= 8.1.8",
  "fsrs~=2.5.1",
  "schema~=0.7.5",
  "tenacity ~= 8.2.3",
]

[project.scripts]
srn-review = "srn.cli:review"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["../LICENSES/*"]

[tool.setuptools.dynamic]
version = { attr = "srn.release.__version__" }

[tool.setuptools.packages.find]
include = ["srn*"]
exclude = ["contrib", "docs", "test*", "node_modules*", "dist"]

[dependency-groups]
dev = ["pre-commit>=4.0.1", "ruff>=0.8.0"]
